name: CI Action
on: push

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#perl-workflow'
      if: always()
    # REF: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#using-the-checkout-action
    - name: "Checkout repository"
      uses: actions/checkout@v2
    - name: "Installing dependencies and testing all using dzil"
      uses: jonasbn/github-action-perl-dist-zilla@master
      with:
          dzil-arguments: 'test --all'
